# Generated by Django 2.2.2 on 2019-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='media_files/recipe_images/no-image.png', upload_to='media_files/recipe_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media_files/profile_image/no-image.png', upload_to='media_files/profile_image'),
        ),
    ]
