# Generated by Django 2.2.2 on 2019-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190614_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='votes_down',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos negativos'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='votes_up',
            field=models.PositiveIntegerField(default=0, verbose_name='Votos positivos'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=144, verbose_name='Descripción'),
        ),
    ]
