# Generated by Django 2.2.2 on 2019-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190615_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='score',
        ),
    ]
