# Generated by Django 2.2.2 on 2019-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190615_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='Usuarios_que_han_votado', to='base.Profile', verbose_name='Usuarios que han votado'),
        ),
    ]
