# Generated by Django 2.2.2 on 2019-06-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=15, verbose_name='Nombre')),
                ('bio', models.TextField(blank=True, max_length=256, verbose_name='Biografía')),
                ('image', models.ImageField(default='media_files/profile_image/no-image.png', upload_to='media_files/profile_image')),
                ('followed', models.ManyToManyField(blank=True, related_name='Seguidos', to='kakigori_users.Profile', verbose_name='Seguidos')),
                ('followers', models.ManyToManyField(blank=True, related_name='Seguidores', to='kakigori_users.Profile', verbose_name='Seguidores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
