# Generated by Django 2.2.2 on 2019-06-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kakigori_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('image', models.ImageField(default='media_files/recipe_images/no-image.png', upload_to='media_files/recipe_images')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.TextField(max_length=512, verbose_name='Descripción')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Tiempo de elaboración (minutos)')),
                ('votes_up', models.PositiveIntegerField(default=0, verbose_name='Votos positivos')),
                ('votes_down', models.PositiveIntegerField(default=0, verbose_name='Votos negativos')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakigori_users.Profile', verbose_name='Autor')),
                ('voters', models.ManyToManyField(blank=True, related_name='Usuarios_que_han_votado', to='kakigori_users.Profile', verbose_name='Usuarios que han votado')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['created_at'],
            },
        ),
    ]
